# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [VOLKANURAL , Wikivu]
patreon: # Replace with a single WiCloudX username
open_collective: # Replace with a single Open Collective username WiCloudX
ko_fi: # Replace with a single WiCloudX username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., WiCloudX
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single WiCloudX username
issuehunt: # Replace with a single WiCloudX username
otechie: # Replace with a single WiCloudX username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single WiCloudX username
custom: # Replace with up to 4 custom sponsorship URLs e.g., [tr.pinterest.com/Wikivolcano,github.com/enterprises/wicloudas']
wikivu
